"""initial schema

Revision ID: 859fa00bda28
Revises: 
Create Date: 2026-05-04 12:08:00.607657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '859fa00bda28'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=500), nullable=False),
    sa.Column('ingestion_status', sa.String(length=20), nullable=True),
    sa.Column('ingestion_error', sa.Text(), nullable=True),
    sa.Column('chapter_count', sa.Integer(), nullable=True),
    sa.Column('topic_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('topic_number', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('key_concepts', sa.JSON(), nullable=True),
    sa.Column('vocabulary', sa.JSON(), nullable=True),
    sa.Column('difficulty_ceiling', sa.String(length=5), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_level', sa.String(length=5), nullable=True),
    sa.Column('consecutive_confident', sa.Integer(), nullable=True),
    sa.Column('questions_asked', sa.Integer(), nullable=True),
    sa.Column('hint_tier', sa.Integer(), nullable=True),
    sa.Column('concept_reset_done', sa.Boolean(), nullable=True),
    sa.Column('flagged_for_review', sa.Boolean(), nullable=True),
    sa.Column('final_confidence', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_mastery',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('mastery_level', sa.String(length=5), nullable=True),
    sa.Column('consecutive_confident', sa.Integer(), nullable=True),
    sa.Column('last_hint_tier_needed', sa.Integer(), nullable=True),
    sa.Column('flagged_for_review', sa.Boolean(), nullable=True),
    sa.Column('last_practiced_at', sa.DateTime(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_name', 'topic_id')
    )
    op.create_table('session_turns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('student_answer', sa.Text(), nullable=True),
    sa.Column('assessment_score', sa.Integer(), nullable=True),
    sa.Column('confidence_tag', sa.String(length=20), nullable=True),
    sa.Column('hint_tier_used', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_turns')
    op.drop_table('topic_mastery')
    op.drop_table('sessions')
    op.drop_table('topics')
    op.drop_table('chapters')
    op.drop_table('books')
    # ### end Alembic commands ###
