"""add_admin_task_tracker

Revision ID: 8fdfaa172fd1
Revises: n6e7f8g9h0i1
Create Date: 2026-06-01 07:50:15.596685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fdfaa172fd1'
down_revision: Union[str, Sequence[str], None] = 'n6e7f8g9h0i1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['admin_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('admin_name', sa.String(length=200), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_name', sa.String(length=200), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_task_dependencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_id'], ['admin_tasks.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['admin_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'depends_on_id')
    )
    op.create_table('admin_task_expenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['admin_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_usage_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('called_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('subjects_json', sa.Text(), nullable=True),
    sa.Column('questions_json', sa.Text(), nullable=False),
    sa.Column('answers_json', sa.Text(), nullable=True),
    sa.Column('scores_json', sa.Text(), nullable=True),
    sa.Column('feedbacks_json', sa.Text(), nullable=True),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_bank',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=5), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('expected_key_points', sa.Text(), nullable=True),
    sa.Column('answer_format', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_text', sa.String(length=300), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('result_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start')
    )
    op.create_table('weekly_challenges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.DateTime(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('expected_key_points', sa.Text(), nullable=True),
    sa.Column('answer_format', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade', 'week_start')
    )
    op.create_table('weekly_challenge_completions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['weekly_challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'challenge_id')
    )
    op.add_column('session_turns', sa.Column('missed_key_points', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('level_question_count', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('diagnostic_phase', sa.Boolean(), nullable=True))
    op.add_column('sessions', sa.Column('diagnostic_turn', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('is_practice', sa.Boolean(), nullable=True))
    op.add_column('sessions', sa.Column('ab_variant', sa.String(length=1), nullable=True))
    op.add_column('topic_mastery', sa.Column('student_id', sa.Integer(), nullable=True))
    op.add_column('topic_mastery', sa.Column('next_review_at', sa.DateTime(), nullable=True))
    op.add_column('topic_mastery', sa.Column('review_interval_days', sa.Integer(), nullable=True))
    op.add_column('topic_mastery', sa.Column('ease_factor', sa.Float(), nullable=True))
    op.add_column('topic_mastery', sa.Column('studied', sa.Boolean(), nullable=True))
    op.add_column('topic_mastery', sa.Column('study_summary', sa.Text(), nullable=True))
    op.add_column('topic_mastery', sa.Column('mastery_confirmed', sa.Boolean(), nullable=True))
    op.add_column('topic_mastery', sa.Column('session_memory', sa.Text(), nullable=True))
    op.drop_constraint(op.f('topic_mastery_student_name_topic_id_key'), 'topic_mastery', type_='unique')
    op.create_unique_constraint(None, 'topic_mastery', ['student_id', 'topic_id'])
    op.create_foreign_key(None, 'topic_mastery', 'users', ['student_id'], ['id'])
    op.add_column('users', sa.Column('total_xp', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('weekly_xp', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('weekly_xp_reset_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('show_on_leaderboard', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('buddy_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('buddy_avatar', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('avatar_preset', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('streak_days', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('streak_freeze_available', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('streak_freeze_used_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('has_onboarded', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('daily_goal_sessions', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('weekly_mastery_goal', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('daily_challenge_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'daily_challenge_date')
    op.drop_column('users', 'weekly_mastery_goal')
    op.drop_column('users', 'daily_goal_sessions')
    op.drop_column('users', 'has_onboarded')
    op.drop_column('users', 'streak_freeze_used_at')
    op.drop_column('users', 'streak_freeze_available')
    op.drop_column('users', 'streak_days')
    op.drop_column('users', 'avatar_preset')
    op.drop_column('users', 'buddy_avatar')
    op.drop_column('users', 'buddy_name')
    op.drop_column('users', 'show_on_leaderboard')
    op.drop_column('users', 'weekly_xp_reset_at')
    op.drop_column('users', 'weekly_xp')
    op.drop_column('users', 'total_xp')
    op.drop_constraint(None, 'topic_mastery', type_='foreignkey')
    op.drop_constraint(None, 'topic_mastery', type_='unique')
    op.create_unique_constraint(op.f('topic_mastery_student_name_topic_id_key'), 'topic_mastery', ['student_name', 'topic_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('topic_mastery', 'session_memory')
    op.drop_column('topic_mastery', 'mastery_confirmed')
    op.drop_column('topic_mastery', 'study_summary')
    op.drop_column('topic_mastery', 'studied')
    op.drop_column('topic_mastery', 'ease_factor')
    op.drop_column('topic_mastery', 'review_interval_days')
    op.drop_column('topic_mastery', 'next_review_at')
    op.drop_column('topic_mastery', 'student_id')
    op.drop_column('sessions', 'ab_variant')
    op.drop_column('sessions', 'is_practice')
    op.drop_column('sessions', 'diagnostic_turn')
    op.drop_column('sessions', 'diagnostic_phase')
    op.drop_column('sessions', 'level_question_count')
    op.drop_column('session_turns', 'missed_key_points')
    op.drop_table('weekly_challenge_completions')
    op.drop_table('weekly_challenges')
    op.drop_table('student_goals')
    op.drop_table('question_bank')
    op.drop_table('exam_sessions')
    op.drop_table('ai_usage_log')
    op.drop_table('admin_task_expenses')
    op.drop_table('admin_task_dependencies')
    op.drop_table('admin_audit_log')
    op.drop_table('admin_tasks')
    # ### end Alembic commands ###
