"""add exercises to topics

Revision ID: a963847deb5a
Revises: 859fa00bda28
Create Date: 2026-05-04 13:09:38.785090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a963847deb5a'
down_revision: Union[str, Sequence[str], None] = '859fa00bda28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('exercises', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'exercises')
    # ### end Alembic commands ###
